sonar.projectKey=MySetsuna_ridge
sonar.projectName=Ridge
sonar.sourceEncoding=UTF-8

sonar.sources=src,packages,src-tauri/src,scripts
sonar.tests=src,packages,scripts
sonar.exclusions=**/*.test.*,**/*.spec.*,**/node_modules/**,**/target/**,**/dist/**,**/remote-dist/**,**/.svelte-kit/**,packages/ridge-term/pkg/**
sonar.test.inclusions=**/*.test.*,**/*.spec.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info
